export const GEARS = {
  "Personaggio": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Jonah",
      "name": "Jonah",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/a0/Jonah.png/revision/latest?cb=20200119155809",
      "upgrade": {
        "Cards": [
          "-",
          "2",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " "
        ],
        "Price":[
          "-",
          "400",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " ",
          " "
        ]
      },
      "skills": {
        "Agilita": [
          2,
          3,
          4,
          6,
          7,
          8,
          9,
          10,
          12,
          13,
          14,
          15,
          17
        ],
        "Resistenza": [
          3,
          4,
          4,
          5,
          6,
          6,
          7,
          8,
          8,
          9,
          10,
          10,
          11
        ],
        "Servizio": [
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        "Volee":[
          2,
          3,
          4,
          4,
          5,
          6,
          6,
          7,
          8,
          8,
          9,
          ,
          
        ],
        "Dritto":[
          5,
          7,
          8,
          9,
          10,
          11,
          13,
          14,
          15,
          16,
          17,
          18,
           
        ],
        "Rovescio": [
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Hope",
      "name": "Hope",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/1/18/Hope.png/revision/latest?cb=20200119155826",
      "upgrade": {
        "Cards": [
          "/",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100"
        ],
        "Price": [
          "/",
          "0.4",
          "1.4k",
          "3.2k",
          "6k",
          "11k",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "66k"
        ]
      },
      "skills": {
        "Agilita": [
          3,
          5,
          7,
          7,
          10,
          11,
          12,
          14,
          16,
          17,
          18,
          x,
          22
        ],
        "Resistenza": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          10,
          11,
          11,
          x,
          14
        ],
        "Servizio": [
          3,
          4,
          5,
          6,
          7,
          8,
          8,
          9,
          10,
          10,
          11,
          x,
          12
        ],
        "Volee": [
          4,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          x,
          14
        ],
        "Dritto": [
          4,
          5,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          14,
          x,
          17
        ],
        "Rovescio": [
          4,
          5,
          6,
          7,
          8,
          8,
          9,
          10,
          11,
          12,
          13,
          x,
          15
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Florence",
      "name": "Florence",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/d/d9/Florence.png/revision/latest?cb=20200119155922",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "120",
          "250"
        ],
        "Price": [
          "/",
          "1.4k",
          "3.2k",
          "6k",
          "11k",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "66k",
          "110k"
        ]
      },
      "skills": {
        "Agilita": [
          5,
          7,
          9,
          11,
          12,
          14,
          16,
          18,
          20,
          21,
          23
        ],
        "Resistenza": [
          7,
          8,
          9,
          10,
          11,
          13,
          14,
          15,
          16,
          17,
          19
        ],
        "Servizio": [
          1,
          2,
          2,
          3,
          3,
          4,
          4,
          5,
          5,
          6,
          7
        ],
        "Volee": [
          2,
          2,
          3,
          4,
          4,
          5,
          5,
          6,
          7,
          7,
          8
        ],
        "Dritto": [
          3,
          4,
          5,
          6,
          7,
          7,
          8,
          9,
          10,
          11,
          12
        ],
        "Rovescio": [
          3,
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          10,
          10,
          11
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Leo",
      "name": "Leo",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/1/1d/Leo.png/revision/latest?cb=20200119154813",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100"
        ],
        "Price": [
          "/",
          "6k",
          "11k",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "66k",
          "86k",
          "110k",
          "180k"
        ]
      },
      "skills": {
        "Agilita": [
          3,
          5,
          6,
          7,
          9,
          10,
          12,
          13,
          15,
          16,
          18
        ],
        "Resistenza": [
          2,
          2,
          3,
          3,
          4,
          5,
          5,
          6,
          6,
          7,
          7
        ],
        "Servizio": [
          5,
          6,
          8,
          9,
          10,
          11,
          12,
          14,
          15,
          16,
          17
        ],
        "Volee": [
          5,
          7,
          8,
          9,
          10,
          11,
          12,
          14,
          15,
          16,
          17
        ],
        "Dritto": [
          4,
          5,
          6,
          7,
          8,
          8,
          9,
          10,
          11,
          12,
          13
        ],
        "Rovescio": [
          3,
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          10,
          10,
          11
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Hyun-Jun",
      "name": "Hyun-Jun",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/f/fa/Hyun-Jun.png/revision/latest?cb=20230302201326",
      "upgrade": {
        "Cards": [
          "/",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100"
          "200"
          "600"
        ],
        "Price": [
          "/",
          "0.4",
          "1.4k",
          "3.2k",
          "6k",
          "11k",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "660k",
          "?"
          "?"
        ]
      },
      "skills": {
        "Agilita": [
          4,
          5,
          6,
          7,
          8,
          ,
          9,
          ,
          ,
          ,
          ,
          ,
          17
        ],
        "Resistenza": [
          4,
          4,
          5,
          5,
          6,
          ,
          7,
          ,
          ,
          ,
          ,
          ,
          11
        ],
        "Servizio": [
          4,
          5,
          6,
          7,
          8,
          ,
          10,
          ,
          ,
          ,
          ,
          ,
          16
        ],
        "Volee": [
          2,
          3,
          4,
          4,
          5,
          ,
          6,
          ,
          ,
          ,
          ,
          ,
          11
        ],
        "Dritto": [
          8,
          9,
          10,
          11,
          12,
          ,
          16,
          ,
          ,
          ,
          ,
          ,
          23
        ],
        "Rovescio": [
          5,
          6,
          7,
          8,
          9,
          ,
          11,
          ,
          ,
          ,
          ,
          ,
          17
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Kaito",
      "name": "Kaito",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/9/92/Kaito.png/revision/latest?cb=20200119155948",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          "750"
        ],
        "Price": [
          "/",
          "6k",
          "11k",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "66k",
          "86k",
          "110k",
          "140k",
          "180k",
          "250k",
          "3.5m",
          "10m"
        ]
      },
      "skills": {
        "Agilita": [
          6,
          7,
          9,
          11,
          12,
          14,
          16,
          18,
          20,
          21,
          23,
          25,
          27,
          28,
          30
        ],
        "Resistenza": [
          6,
          8,
          9,
          10,
          11,
          13,
          14,
          15,
          16,
          17,
          19,
          20,
          21,
          22,
          24
        ],
        "Servizio": [
          1,
          2,
          2,
          3,
          3,
          4,
          4,
          5,
          5,
          6,
          7,
          7,
          8,
          8,
          9
        ],
        "Volee": [
          2,
          3,
          4,
          4,
          5,
          6,
          6,
          7,
          8,
          8,
          9,
          10,
          10,
          11,
          12
        ],
        "Dritto": [
          3,
          4,
          5,
          6,
          7,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          13,
          14,
          15
        ],
        "Rovescio": [
          3,
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          10,
          10,
          11,
          12,
          13,
          14,
          15
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Viktoria",
      "name": "Viktoria",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/2/29/Viktoria.png/revision/latest?cb=20200119160110",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          "750"
        ],
        "Price": [
          "/",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "66k",
          "86k",
          "110k",
          "140k",
          "180k",
          "210k",
          "250k",
          "440k",
          "2m",
          "10m"
        ]
      },
      "skills": {
        "Agilita": [
          3,
          5,
          6,
          6,
          7,
          8,
          9,
          10,
          12,
          13,
          14,
          16,
          17,
          18,
          19
        ],
        "Resistenza": [
          2,
          2,
          3,
          5,
          6,
          6,
          7,
          8,
          8,
          9,
          10,
          10,
          11,
          12,
          12
        ],
        "Servizio": [
          5,
          7,
          8,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17
        ],
        "Volee": [
          6,
          7,
          8,
          4,
          5,
          6,
          6,
          7,
          8,
          8,
          9,
          10,
          10,
          12,
          12
        ],
        "Dritto": [
          3,
          4,
          5,
          10,
          11,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          22,
          23,
          24
        ],
        "Rovescio": [
          3,
          4,
          5,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Diana",
      "name": "Diana",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/5/5f/Diana.png/revision/latest?cb=20200119155840",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "120",
          "240",
          "450",
          "750"
        ],
        "Price": [
          "/",
          "52k",
          "66k",
          "86k",
          "110k",
          "140k",
          "180k",
          "210k",
          "250k",
          "280k",
          "360k",
          "440k",
          "700k",
          "2.5m",
          "10m"
        ]
      },
      "skills": {
        "Agilita": [
          4,
          5,
          7,
          8,
          10,
          11,
          13,
          14,
          16,
          17,
          19,
          20,
          22,
          24,
          25
        ],
        "Resistenza": [
          1,
          2,
          2,
          3,
          3,
          4,
          4,
          4,
          5,
          5,
          6,
          6,
          7,
          7,
          8
        ],
        "Servizio": [
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          15,
          16,
          17,
          18,
          19,
          20
        ],
        "Volee": [
          6,
          7,
          8,
          9,
          11,
          12,
          13,
          14,
          16,
          17,
          18,
          19,
          20,
          22,
          23
        ],
        "Dritto": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          10,
          11,
          12,
          13,
          14,
          15,
          16
        ],
        "Rovescio": [
          3,
          4,
          5,
          6,
          7,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          14,
          15
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Mei-Li",
      "name": "Mei-Li",
      "foundIn": "Tour 7 and above",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/5/58/Mei-Li.png/revision/latest?cb=20200129205010",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          "750"
        ],
        "Price": [
          "",
          "140k",
          "180k",
          "210k",
          "250k",
          "280k",
          "360k",
          "440k",
          "520k",
          "600k",
          "700k",
          "800k",
          "1000k",
          "3.5m",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          3,
          5,
          6,
          7,
          9,
          10,
          12,
          13,
          15,
          16,
          18,
          19,
          21,
          22,
          23
        ],
        "Resistenza": [
          3,
          4,
          5,
          6,
          6,
          7,
          8,
          9,
          9,
          10,
          11,
          12,
          12,
          13,
          14
        ],
        "Servizio": [
          3,
          4,
          4,
          5,
          6,
          7,
          8,
          8,
          9,
          10,
          11,
          12,
          12,
          13,
          14
        ],
        "Volee": [
          4,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          12,
          13,
          14,
          15,
          16
        ],
        "Dritto": [
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          12,
          13,
          14,
          13,
          13,
          17,
          18,
          19
        ],
        "Rovescio": [
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          11,
          12,
          15,
          16,
          17
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Luc",
      "name": "Luc",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/b/bc/Luc.png/revision/latest?cb=20200319135439",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          "750"
        ],
        "Price": [
          "/",
          "140k",
          "180k",
          "210k",
          "250k",
          "280k",
          "360k",
          "440k",
          "520k",
          "600k",
          "700k",
          "800k",
          "1000k",
          "",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          3,
          4,
          5,
          7,
          8,
          9,
          11,
          12,
          13,
          15,
          16,
          17,
          19,
          20,
          21
        ],
        "Resistenza": [
          2,
          3,
          4,
          4,
          5,
          5,
          6,
          7,
          7,
          8,
          8,
          9,
          10,
          10,
          11
        ],
        "Servizio": [
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18
        ],
        "Volee": [
          2,
          3,
          3,
          4,
          4,
          5,
          6,
          6,
          7,
          8,
          8,
          9,
          10,
          11,
          11
        ],
        "Dritto": [
          6,
          7,
          9,
          10,
          11,
          12,
          14,
          15,
          16,
          18,
          19,
          20,
          21,
          22,
          24
        ],
        "Rovescio": [
          4,
          5,
          6,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Abeke",
      "name": "Abeke",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/9/99/Abeke2.png/revision/latest?cb=20220702175508",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          "750"
        ],
        "Price": [
          "/",
          "52k",
          "86k",
          "110k",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          6,
          8,
          10,
          12,
          14,
          16,
          17,
          19,
          21,
          23,
          25,
          26,
          28,
          30,
          32
        ],
        "Resistenza": [
          7,
          8,
          9,
          10,
          12,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          22,
          23,
          24
        ],
        "Servizio": [
          4,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          13,
          14,
          15,
          16
        ],
        "Volee": [
          2,
          2,
          3,
          4,
          4,
          5,
          5,
          6,
          7,
          7,
          8,
          9,
          9,
          10,
          10
        ],
        "Dritto": [
          3,
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          10,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        "Rovescio": [
          4,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Omar",
      "name": "Omar",
      "foundIn": "",
      "rarity": "",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/3/3d/Omar_Polishing_WIP_1.png/revision/latest?cb=20210908140518",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "3",
          "4",
          "5",
          "8",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          "750"
        ],
        "Price": [
          "/",
          "11k",
          "17.2k",
          "26k",
          "36k",
          "52k",
          "66k",
          "86k",
          "110k",
          "140k",
          "180k",
          "210k",
          "360k",
          "",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          3,
          5,
          6,
          8,
          9,
          11,
          12,
          14,
          15,
          17,
          19,
          21,
          21,
          22,
          24
        ],
        "Resistenza": [
          2,
          2,
          3,
          3,
          4,
          4,
          5,
          5,
          6,
          6,
          6,
          7,
          8,
          9,
          9
        ],
        "Servizio": [
          5,
          7,
          8,
          9,
          10,
          11,
          13,
          14,
          15,
          16,
          17,
          18,
          20,
          21,
          22
        ],
        "Volee": [
          6,
          7,
          8,
          9,
          10,
          12,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          21,
          22
        ],
        "Dritto": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          11,
          13,
          14,
          14,
          15,
          16
        ],
        "Rovescio": [
          3,
          4,
          5,
          5,
          6,
          7,
          8,
          9,
          9,
          10,
          11,
          12,
          13,
          14,
          14
        ]
      }
    }
  ],
  "Racchetta": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Starter_Racket",
      "name": "Racchetta iniziale",
      "foundIn": "Start",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/b/ba/Starter_Racket.png/revision/latest?cb=20200119161107",
      "upgrade": {},
      "skills": {
        "Dritto": [
          3
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Bullseye",
      "name": "Il bersaglio",
      "foundIn": "Tour 7",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/ae/The_Bullseye.png/revision/latest?cb=20200119172849",
      "upgrade": {
        "Cards": [
          "Starter",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "",
          ""
        ],
        "Price": [
          "/",
          "",
          "",
          "",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "216.7k",
          "250k",
          "291.7k",
          "333.4k",
          "416.7k",
          "",
          ""
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          0,
          17,
          21,
          26,
          30,
          33,
          37,
          40,
          43,
          46,
          49,
          52,
          55
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Eagle",
      "name": "L'aquila",
      "foundIn": "Tour 1 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/1/18/The_Eagle.png/revision/latest?cb=20200119160844",
      "upgrade": {
        "Cards": [
          "Starter",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "/",
          "",
          "600",
          "1.4k",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k"
        ]
      },
      "skills": {
        "Agilita": [
          2,
          3,
          3,
          3,
          3,
          3,
          3,
          3,
          4,
          4,
          4
        ],
        "Dritto": [
          3,
          4,
          7,
          10,
          14,
          19,
          23,
          26,
          29,
          31,
          34
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Hammer",
      "name": "Il martello",
      "foundIn": "Tour 6",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/3/3a/The_Hammer.png/revision/latest?cb=20200119171931",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "45.9K",
          "58.4K",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "216.7k",
          "750k",
          ""
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          0,
          7,
          8,
          8,
          8,
          8,
          9,
          10,
          10,
          11,
          12,
          12,
          13
        ],
        "Dritto": [
          0,
          0,
          0,
          14,
          18,
          22,
          27,
          30,
          32,
          35,
          38,
          41,
          44,
          47,
          50
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Outback",
      "name": "L'entroterra",
      "foundIn": "Tour 3 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/a1/The_Outback.png/revision/latest?cb=20200119163206",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "75k"
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          0,
          10,
          10,
          10,
          10,
          11,
          12,
          13,
          14
        ],
        "Dritto": [
          0,
          0,
          0,
          6,
          10,
          14,
          18,
          21,
          23,
          24,
          27
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Panther",
      "name": "La pantera",
      "foundIn": "Tour 4 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/2/27/The_Panther.png/revision/latest?cb=20200119163628",
      "upgrade": {
        "Cards": [
          "L",
          "L",
          "UL",
          "2",
          "4",
          "10",
          "30",
          "60",
          "150",
          "400",
          "800"
        ],
        "Price": [
          "",
          "",
          "",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "104.2k"
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          12,
          16,
          20,
          25,
          29,
          32,
          35,
          38,
          42
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Patriot",
      "name": "Il patriota",
      "foundIn": "Tour 2 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/8/88/The_Patriot.png/revision/latest?cb=20200119170819",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "45.9k"
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          0,
          7,
          7,
          7,
          7,
          8,
          8,
          8,
          9
        ],
        "Dritto": [
          0,
          0,
          0,
          13,
          17,
          21,
          26,
          29,
          32,
          35,
          37
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Samurai",
      "name": "Il Samurai",
      "foundIn": "Tour 5 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/4/4b/The_Samurai.png/revision/latest?cb=20200119164010",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "1.5k",
          "5k"
        ],
        "Price": [
          "",
          "",
          "",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104,2k",
          "183.4k",
          "",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          0,
          0,
          3,
          3,
          3,
          3,
          3,
          4,
          4,
          4,
          5,
          5,
          5,
          6,
          6
        ],
        "Dritto": [
          0,
          0,
          6,
          9,
          14,
          18,
          23,
          25,
          28,
          31,
          33,
          36,
          38,
          41,
          43
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Zeus",
      "name": "Zeus",
      "foundIn": "Tour 8",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/3/3c/Zeus.png/revision/latest?cb=20200119174426",
      "upgrade": {
        "Cards": [
          "0",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "2k",
          "4k",
          "",
          ""
        ],
        "Price": [
          "0",
          "150k",
          "180k",
          "210k",
          "230K",
          "250k",
          "300K",
          "380k",
          "450K",
          "530K",
          "560K",
          "600K",
          "700K",
          "1.85m",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          5,
          5,
          6,
          7,
          7,
          7,
          7,
          8,
          9,
          9,
          10,
          10,
          11,
          12,
          12
        ],
        "Dritto": [
          0,
          1,
          2,
          6,
          10,
          14,
          18,
          21,
          23,
          25,
          27,
          29,
          32,
          34,
          36
        ]
      }
    }
  ],
  "Grip": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Starter_Grip",
      "name": "Grip iniziale",
      "foundIn": "Start",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/6/62/Starter_Grip.png/revision/latest?cb=20200119180605",
      "upgrade": {},
      "skills": {
        "Rovescio": [
          3
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Tactical_Grip",
      "name": "Grip tattico",
      "foundIn": "Tour 7",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/9/99/Tactical_Grip.png/revision/latest?cb=20200119183439",
      "upgrade": {
        "Cards": [
          "0",
          "0",
          "0",
          "0",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4K",
          "216.7k",
          "250k",
          "291.7K",
          "333.4K",
          "416.7K",
          "1.2m",
          ""
        ]
      },
      "skills": {
        "Volee": [
          8,
          9,
          10,
          11,
          11,
          12,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          19
        ],
        "Rovescio": [
          0,
          1,
          2,
          6,
          10,
          14,
          18,
          21,
          23,
          25,
          27,
          29,
          32,
          34,
          36
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Cobra",
      "name": "Il cobra",
      "foundIn": "Tour 4 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/f/f1/The_Cobra.png/revision/latest?cb=20200119165513",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "104.2k"
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          0,
          10,
          10,
          10,
          10,
          11,
          12,
          13,
          14
        ],
        "Rovescio": [
          0,
          0,
          0,
          6,
          10,
          14,
          18,
          21,
          23,
          24,
          27
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Forge",
      "name": "La fucina",
      "foundIn": "Tour 6 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/8/86/The_Forge.png/revision/latest?cb=20200119183013",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "450",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "291.7k",
          "750k",
          ""
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          0,
          7,
          8,
          8,
          8,
          8,
          9,
          10,
          10,
          11,
          12,
          12,
          13
        ],
        "Rovescio": [
          0,
          0,
          0,
          14,
          18,
          22,
          27,
          30,
          32,
          35,
          38,
          41,
          44,
          47,
          50
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Katana",
      "name": "La katana",
      "foundIn": "Tour 5 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/7/7b/The_Katana.png/revision/latest?cb=20200119180752",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75.0k",
          "87.5k",
          "104.2k",
          "183.4K",
          "",
          ""
        ]
      },
      "skills": {
        "Volee": [
          0,
          0,
          5,
          5,
          5,
          6,
          6,
          6,
          7,
          7,
          8,
          8,
          9,
          9,
          9
        ],
        "Rovescio": [
          0,
          0,
          6,
          10,
          14,
          18,
          23,
          25,
          28,
          31,
          33,
          36,
          38,
          40,
          43
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Machete",
      "name": "Il machete",
      "foundIn": "Tour 3 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/d/df/The_Machete.png/revision/latest?cb=20200119181219",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "150",
          "400",
          "800"
        ],
        "Price": [
          "",
          "",
          "",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "75k"
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          12,
          16,
          20,
          25,
          29,
          32,
          35,
          38,
          42
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Talon",
      "name": "L'artiglio",
      "foundIn": "Tour 2 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/c/c2/The_Talon.png/revision/latest?cb=20200119181315",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5K",
          "45.9k"
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          0,
          7,
          7,
          7,
          7,
          8,
          8,
          9,
          9
        ],
        "Rovescio": [
          0,
          0,
          0,
          13,
          17,
          21,
          26,
          29,
          32,
          34,
          37
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Titan",
      "name": "Il titano",
      "foundIn": "Tour 8",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/7/71/The_Titan.png/revision/latest?cb=20200119182008",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "230K",
          "250K",
          "300K",
          "380k",
          "450k",
          "530k",
          "560k",
          "600k",
          "700k",
          "",
          ""
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          0,
          17,
          21,
          26,
          30,
          33,
          37,
          40,
          43,
          46,
          49,
          52,
          55
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Warrior",
      "name": "Il guerriero",
      "foundIn": "Tour 1 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/d/dd/The_Warrior.png/revision/latest?cb=20200119181657",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1000",
          "2000"
        ],
        "Price": [
          "",
          "200",
          "600",
          "1.4k",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k"
        ]
      },
      "skills": {
        "Volee": [
          3,
          4,
          4,
          5,
          5,
          5,
          5,
          6,
          6,
          6,
          7
        ],
        "Rovescio": [
          3,
          5,
          7,
          10,
          14,
          19,
          23,
          26,
          29,
          31,
          34
        ]
      }
    }
  ],
  "Scarpe": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Starter_Shoes",
      "name": "Scarpe iniziali",
      "foundIn": "Start",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/1/1b/Starter_Shoe.png/revision/latest?cb=20200119185209",
      "upgrade": {},
      "skills": {
        "Agilita": [
          1
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Anvil",
      "name": "L'incudine",
      "foundIn": "Tour 6",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/a8/The_Anvil.png/revision/latest?cb=20200119193426",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "1.5k",
          "5k"
        ],
        "Price": [
          "",
          "",
          "",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "216.7k",
          "750k",
          "5m"
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          5,
          6,
          6,
          6,
          6,
          7,
          7,
          8,
          8,
          9,
          10,
          10,
          11
        ],
        "Agilita": [
          0,
          0,
          7,
          11,
          15,
          19,
          23,
          27,
          30,
          33,
          36,
          40,
          43,
          46,
          50
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Ballistic",
      "name": "La balistica",
      "foundIn": "Tour 7 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/b/b7/The_Balistic.png/revision/latest?cb=20200119193138",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "1.5k",
          "5k"
        ],
        "Price": [
          "",
          "",
          "",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "216.7k",
          "250k",
          "291.7k",
          "333.4k",
          "416.7k",
          "750k",
          "5m"
        ]
      },
      "skills": {
        "Servizio": [
          0,
          0,
          5,
          5,
          6,
          6,
          6,
          6,
          7,
          7,
          8,
          8,
          9,
          9,
          10
        ],
        "Agilita": [
          0,
          0,
          7,
          11,
          15,
          19,
          23,
          27,
          30,
          33,
          36,
          40,
          43,
          46,
          50
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Feather",
      "name": "La piuma",
      "foundIn": "Tour 1 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/1/19/The_Feather.png/revision/latest?cb=20200119192517",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k"
        ]
      },
      "skills": {
        "Agilita": [
          0,
          0,
          0,
          15,
          19,
          23,
          28,
          32,
          35,
          40,
          43
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Hades_Treads",
      "name": "I percorsi di Ade",
      "foundIn": "Tour 8",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/f/f4/Hades_Treads.png/revision/latest?cb=20200119193746",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "230k",
          "250k",
          "300k",
          "380k",
          "450k",
          "530k",
          "560k",
          "600k",
          "700k",
          "1.85m",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          0,
          0,
          0,
          15,
          20,
          24,
          29,
          32,
          36,
          40,
          44,
          47,
          51,
          55,
          58
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Hunter",
      "name": "Il cacciatore",
      "foundIn": "Tour 3 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/1/1b/The_Hunter.png/revision/latest?cb=20200119192607",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "75k"
        ]
      },
      "skills": {
        "Servizio": [
          3,
          4,
          5,
          5,
          5,
          5,
          5,
          6,
          6,
          7,
          7
        ],
        "Agilita": [
          5,
          6,
          7,
          11,
          15,
          19,
          24,
          27,
          30,
          34,
          37
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Piranha",
      "name": "Il piragna",
      "foundIn": "Tour 4 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/6/69/The_Piranha.png/revision/latest?cb=20200119192707",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "104.2k"
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          0,
          12,
          12,
          13,
          13,
          14,
          15,
          16,
          17
        ],
        "Agilita": [
          0,
          0,
          0,
          8,
          12,
          16,
          20,
          23,
          26,
          29,
          32
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Raptor",
      "name": "Il rapace",
      "foundIn": "Tour 2 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/3/33/The_Raptor.png/revision/latest?cb=20200119194149",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "",
          "0.6k",
          "1.4k",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "45.9k"
        ]
      },
      "skills": {
        "Resistenza": [
          3,
          4,
          5,
          5,
          5,
          6,
          6,
          6,
          7,
          7,
          8
        ],
        "Agilita": [
          1,
          4,
          7,
          11,
          15,
          19,
          24,
          27,
          30,
          34,
          37
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Shuriken",
      "name": "La shuriken",
      "foundIn": "Tour 5 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/4/42/The_Shuriken.png/revision/latest?cb=20200119193927",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "183.4k",
          "",
          ""
        ]
      },
      "skills": {
        "Servizio": [
          0,
          0,
          0,
          11,
          12,
          12,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20
        ],
        "Agilita": [
          0,
          0,
          0,
          8,
          12,
          16,
          20,
          23,
          26,
          29,
          32,
          35,
          38,
          41,
          44
        ]
      }
    }
  ],
  "Polsiera": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Starter_Band",
      "name": "Iniziale",
      "foundIn": "Start",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/0/03/Starter_Band.png/revision/latest?cb=20200119212711",
      "upgrade": {},
      "skills": {
        "Volee": [
          0
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Jolly_Roger",
      "name": "Bandiera pirata",
      "foundIn": "Tour 3 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/8/8f/Jolly_Roger.png/revision/latest?cb=20200119212854",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "75k"
        ]
      },
      "skills": {
        "Servizio": [
          0,
          0,
          0,
          11,
          12,
          12,
          12,
          13,
          14,
          15,
          16
        ],
        "Volee": [
          0,
          0,
          0,
          2,
          5,
          9,
          14,
          16,
          18,
          19,
          22
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Gladiator",
      "name": "Il gladiatore",
      "foundIn": "Tour 7 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/9/98/The_Gladiator.png/revision/latest?cb=20200119213722",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          "1000"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "216.7k",
          "250k",
          "291.7k",
          "333.4k",
          "416.7k",
          "500k",
          "800k"
        ]
      },
      "skills": {
        "Volee": [
          0,
          0,
          0,
          14,
          18,
          23,
          27,
          30,
          33,
          36,
          39,
          43,
          46,
          49,
          52
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Kodiak",
      "name": "L'orso Kodiak",
      "foundIn": "Tour 6 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/2/26/The_Kodiak.png/revision/latest?cb=20200119213602",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "1.5k",
          "2k"
        ],
        "Price": [
          "",
          "",
          "",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "291.7k",
          "750k",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          0,
          0,
          3,
          3,
          3,
          3,
          3,
          4,
          4,
          4,
          5,
          5,
          5,
          6,
          6
        ],
        "Volee": [
          0,
          0,
          3,
          6,
          10,
          14,
          19,
          21,
          24,
          26,
          28,
          31,
          33,
          36,
          38
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Koi",
      "name": "Il koi",
      "foundIn": "Tour 5 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/0/0a/The_Koi.png/revision/latest?cb=20200119213437",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "21.7K",
          "27.5K",
          "35.9K",
          "45.9K",
          "58.4K",
          "75K",
          "87.5K",
          "104.2k",
          "183.4k",
          "500k",
          ""
        ]
      },
      "skills": {
        "Agilita": [
          0,
          0,
          0,
          7,
          7,
          7,
          7,
          8,
          9,
          9,
          10,
          10,
          11,
          12,
          12
        ],
        "Volee": [
          0,
          0,
          0,
          2,
          5,
          9,
          14,
          16,
          18,
          20,
          22,
          24,
          26,
          28,
          30
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Macaw",
      "name": "Il pappagallo ara",
      "foundIn": "Tour 4 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/6/6b/The_Macaw.png/revision/latest?cb=20200119213314",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "104.2k"
        ]
      },
      "skills": {
        "Servizio": [
          3,
          4,
          4,
          5,
          5,
          5,
          5,
          6,
          6,
          7,
          7
        ],
        "Volee": [
          0,
          2,
          3,
          7,
          11,
          15,
          19,
          22,
          24,
          27,
          29
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Rocket",
      "name": "Il razzo",
      "foundIn": "Tour 2 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/af/The_Rocket.png/revision/latest?cb=20200119213210",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "",
          "600",
          "1.4k",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9K",
          "15k",
          "21.7k",
          "27.5k",
          "45.9k"
        ]
      },
      "skills": {
        "Agilita": [
          2,
          3,
          3,
          3,
          3,
          3,
          3,
          3,
          4,
          4,
          4
        ],
        "Volee": [
          0,
          1,
          3,
          6,
          11,
          15,
          19,
          22,
          24,
          27,
          29
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Shield",
      "name": "Lo scudo",
      "foundIn": "Tour 8",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/3/3b/The_Shield.png/revision/latest?cb=20200119214118",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "1.5k",
          "5k"
        ],
        "Price": [
          "",
          "",
          "",
          "210k",
          "230k",
          "250k",
          "300k",
          "380k",
          "450k",
          "530k",
          "560k",
          "600k",
          "700k",
          "",
          "7.5m"
        ]
      },
      "skills": {
        "Servizio": [
          0,
          0,
          5,
          5,
          6,
          6,
          6,
          6,
          7,
          7,
          8,
          8,
          9,
          9,
          10
        ],
        "Volee": [
          0,
          0,
          3,
          6,
          10,
          14,
          19,
          21,
          24,
          26,
          28,
          31,
          33,
          36,
          38
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/The_Tomahawk",
      "name": "Il Tomahawk",
      "foundIn": "Tour 1 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/2/22/The_Tomahawk.png/revision/latest?cb=20200119213054",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k"
        ]
      },
      "skills": {
        "Volee": [
          0,
          0,
          0,
          13,
          17,
          21,
          26,
          29,
          32,
          34,
          38
        ]
      }
    }
  ],
  "Nutrizione": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Starter_Protein",
      "name": "Proteine iniziali",
      "foundIn": "Start",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/4/4d/Starter_Protein.png/revision/latest?cb=20200120004110",
      "upgrade": {},
      "skills": {
        "Resistenza": [
          0
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Antioxidants",
      "name": "Antiossidanti",
      "foundIn": "Tour 6",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/ab/Antioxidants.png/revision/latest?cb=20200120003733",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "2k",
          "4k",
          "7k",
          "25k"
        ],
        "Price": [
          "",
          "21.7K",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "291.7k",
          "750k",
          "3m"
        ]
      },
      "skills": {
        "Dritto": [
          3,
          3,
          4,
          5,
          5,
          5,
          5,
          5,
          6,
          6,
          7,
          7,
          7,
          8,
          8
        ],
        "Resistenza": [
          0,
          1,
          3,
          6,
          9,
          13,
          17,
          19,
          21,
          23,
          26,
          28,
          30,
          32,
          34
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Carboload",
      "name": "Carico di carboidrati",
      "foundIn": "Tour 7",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/5/55/Carboload.png/revision/latest?cb=20200120003547",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "216.7k",
          "250k",
          "291.7k",
          "333.4k",
          "416.7k",
          "1.2m",
          ""
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          0,
          10,
          10,
          10,
          10,
          11,
          12,
          13,
          14,
          15,
          15,
          16,
          17
        ],
        "Resistenza": [
          0,
          0,
          0,
          1,
          4,
          7,
          11,
          13,
          15,
          17,
          18,
          20,
          22,
          24,
          25
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Increased_Hydration",
      "name": "Idratazione aumentata",
      "foundIn": "Tour 2 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/d/d0/Increased_Hydration.png/revision/latest?cb=20200120003908",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "150",
          "400",
          "800"
        ],
        "Price": [
          "",
          "",
          "",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "45.9k"
        ]
      },
      "skills": {
        "Dritto": [
          0,
          0,
          4,
          4,
          4,
          4,
          4,
          5,
          5,
          6,
          6
        ],
        "Resistenza": [
          0,
          0,
          3,
          6,
          10,
          13,
          18,
          20,
          22,
          24,
          26
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Keto_Sourcing",
      "name": "Dieta keto",
      "foundIn": "Tour 5 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/e/ef/Keto_Sourcing.png/revision/latest?cb=20200120004017",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "183.4k",
          "",
          ""
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          0,
          14,
          18,
          22,
          26,
          29,
          32,
          35,
          38,
          41,
          44,
          47,
          49
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Lean_Protein",
      "name": "Proteina magra",
      "foundIn": "Tour 1 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/d/dc/Lean_Protein.png/revision/latest?cb=20200120004222",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k"
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          0,
          13,
          17,
          21,
          25,
          28,
          31,
          34,
          36
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Macrobiotic",
      "name": "Macrobiotico",
      "foundIn": "Tour 3 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/4/4d/Macrobiotic.png/revision/latest?cb=20200120004328",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k"
        ]
      },
      "skills": {
        "Volee": [
          0,
          0,
          0,
          11,
          11,
          12,
          12,
          13,
          14,
          15,
          16
        ],
        "Resistenza": [
          0,
          0,
          0,
          1,
          4,
          7,
          11,
          13,
          15,
          17,
          18
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Natural_Energy",
      "name": "Energia naturale",
      "foundIn": "Tour 7 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/7/77/Natural_Energy.png/revision/latest?cb=20200120003344",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "1.5k",
          "5k"
        ],
        "Price": [
          "",
          "",
          "",
          "210k",
          "230k",
          "250K",
          "300k",
          "380k",
          "450k",
          "530k",
          "560k",
          "600k",
          "700k",
          "1.85k",
          "7.5m"
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          3,
          6,
          9,
          13,
          17,
          19,
          21,
          23,
          26,
          28,
          30,
          32,
          34
        ],
        "Volee": [
          0,
          0,
          5,
          5,
          5,
          6,
          6,
          6,
          7,
          7,
          8,
          8,
          9,
          9,
          9
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Vegan_Diet",
      "name": "Dieta vegana",
      "foundIn": "Tour 4 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/3/36/Vegan_Diet.png/revision/latest?cb=20200120004146",
      "upgrade": {
        "Cards": [
          "L",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "",
          "7.2k",
          "10.9k",
          "15k",
          "21,7k",
          "27,5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "104.2k"
        ]
      },
      "skills": {
        "Volee": [
          3,
          4,
          4,
          5,
          5,
          5,
          5,
          6,
          6,
          6,
          7
        ],
        "Resistenza": [
          0,
          2,
          3,
          6,
          10,
          13,
          18,
          20,
          22,
          24,
          26
        ]
      }
    }
  ],
  "Allenamento": [
    {
      "url": "https://tennis-clash.fandom.com/wiki/Starter_Training",
      "name": "Allenamento iniziale",
      "foundIn": "Start",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/ac/Starter_Training.png/revision/latest?cb=20200120002723",
      "upgrade": {},
      "skills": {
        "Servizio": [
          1
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Endurance",
      "name": "Resistenza",
      "foundIn": "Tour 1 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/0/0a/Endurance.png/revision/latest?cb=20200120002438",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "150",
          "400",
          "800"
        ],
        "Price": [
          "",
          "",
          "",
          "1.4k",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k"
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          5,
          5,
          5,
          6,
          6,
          6,
          7,
          7,
          8
        ],
        "Servizio": [
          0,
          0,
          4,
          8,
          12,
          16,
          21,
          24,
          26,
          29,
          31
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Lunges",
      "name": "Affondi",
      "foundIn": "Tour 8",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/8/87/Lunges.png/revision/latest?cb=20200120002857",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "230K",
          "250k",
          "300k",
          "380k",
          "450k",
          "530k",
          "560k",
          "600k",
          "700k",
          "",
          ""
        ]
      },
      "skills": {
        "Servizio": [
          0,
          0,
          0,
          15,
          20,
          24,
          29,
          32,
          35,
          39,
          42,
          45,
          48,
          51,
          54
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Mountain_Climber",
      "name": "Arrampicatore",
      "foundIn": "Tour 7 and above",
      "rarity": "Rare",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/8/80/Mountain_Climber.png/revision/latest?cb=20200120003033",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "87.5k",
          "104k",
          "116k",
          "150k",
          "183.4k",
          "216.7k",
          "250k",
          "291.7k",
          "333.4k",
          "416.7k",
          "",
          ""
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          4,
          5,
          5,
          5,
          5,
          5,
          6,
          6,
          7,
          7,
          7,
          7,
          8
        ],
        "Servizio": [
          0,
          0,
          4,
          7,
          11,
          16,
          21,
          23,
          25,
          28,
          30,
          33,
          35,
          38,
          40
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Plyometrics",
      "name": "Pliometria",
      "foundIn": "Tour 3 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/a/ac/Plyometrics.png/revision/latest?cb=20200120002534",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "150",
          "400",
          "800",
          "1k",
          "2k"
        ],
        "Price": [
          "",
          "2.5k",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "75k"
        ]
      },
      "skills": {
        "Rovescio": [
          3,
          3,
          4,
          4,
          4,
          4,
          4,
          5,
          5,
          6,
          6
        ],
        "Servizio": [
          1,
          3,
          4,
          8,
          12,
          16,
          21,
          24,
          26,
          29,
          31
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Powerlifting",
      "name": "Powerlifting",
      "foundIn": "Tour 4 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/e/e0/Powerlifting.png/revision/latest?cb=20200120002611",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "104.2k"
        ]
      },
      "skills": {
        "Resistenza": [
          0,
          0,
          0,
          12,
          12,
          13,
          13,
          14,
          15,
          16,
          17
        ],
        "Servizio": [
          0,
          0,
          0,
          2,
          6,
          11,
          15,
          18,
          20,
          22,
          24
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Resistance_Band",
      "name": "Fascia di resistenza",
      "foundIn": "Tour 6 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/6/67/Resistance_Band.png/revision/latest?cb=20200120003159",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "20",
          "40",
          "60",
          "100",
          "150",
          "300",
          "500",
          ""
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "116.7k",
          "150k",
          "183.4k",
          "291.7k",
          "750k",
          ""
        ]
      },
      "skills": {
        "Rovescio": [
          0,
          0,
          0,
          10,
          10,
          10,
          10,
          11,
          12,
          13,
          14,
          15,
          15,
          16,
          17
        ],
        "Servizio": [
          0,
          0,
          0,
          3,
          6,
          11,
          15,
          18,
          20,
          22,
          24,
          26,
          28,
          30,
          32
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Sprint",
      "name": "Sprint",
      "foundIn": "Tour 2 and above",
      "rarity": "Epic",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/b/bb/Sprint.png/revision/latest?cb=20200120002656",
      "upgrade": {
        "Cards": [
          "",
          "",
          "",
          "",
          "2",
          "4",
          "10",
          "30",
          "60",
          "120",
          "240"
        ],
        "Price": [
          "",
          "",
          "",
          "",
          "4.6k",
          "7.2k",
          "10.9k",
          "15k",
          "21.7k",
          "27.5k",
          "45.9k"
        ]
      },
      "skills": {
        "Servizio": [
          0,
          0,
          0,
          14,
          19,
          23,
          28,
          31,
          34,
          36,
          40
        ]
      }
    },
    {
      "url": "https://tennis-clash.fandom.com/wiki/Weight_lifting",
      "name": "Sollevamento pesi",
      "foundIn": "Tour 5 and above",
      "rarity": "Common",
      "imageUrl": "https://vignette.wikia.nocookie.net/tennis-clash/images/e/e2/Weight_Lifting.png/revision/latest?cb=20200120002758",
      "upgrade": {
        "Cards": [
          "",
          "2",
          "4",
          "10",
          "20",
          "50",
          "100",
          "200",
          "400",
          "800",
          "1k",
          "2k",
          "4k",
          "7k",
          "15k"
        ],
        "Price": [
          "",
          "10.9k",
          "12k",
          "15k",
          "21.7k",
          "27.5k",
          "35.9k",
          "45.9k",
          "58.4k",
          "75k",
          "87.5k",
          "104.2k",
          "183.4k",
          "500k",
          ""
        ]
      },
      "skills": {
        "Resistenza": [
          4,
          5,
          5,
          6,
          6,
          6,
          6,
          7,
          7,
          8,
          8,
          9,
          10,
          10,
          11
        ],
        "Servizio": [
          1,
          2,
          4,
          7,
          11,
          16,
          21,
          23,
          25,
          28,
          30,
          33,
          35,
          38,
          40
        ]
      }
    }
  ]
};
